<?php

namespace Database\Seeders;

use App\Models\City;
use App\Models\Governorate;
use Illuminate\Database\Seeder;
use Illuminate\Support\Str;

class CitySeeder extends Seeder
{
    public function run(): void
    {
        $citiesByGovernorate = [
            'cairo' => [
                ['en' => 'Nasr City', 'ar' => 'مدينة نصر'],
                ['en' => 'Heliopolis', 'ar' => 'مصر الجديدة'],
                ['en' => 'Maadi', 'ar' => 'المعادي'],
                ['en' => 'Zamalek', 'ar' => 'الزمالك'],
                ['en' => 'Downtown Cairo', 'ar' => 'وسط البلد'],
                ['en' => 'New Cairo', 'ar' => 'القاهرة الجديدة'],
                ['en' => 'Shubra', 'ar' => 'شبرا'],
                ['en' => 'Helwan', 'ar' => 'حلوان'],
                ['en' => 'Ain Shams', 'ar' => 'عين شمس'],
                ['en' => 'El Marg', 'ar' => 'المرج'],
                ['en' => 'El Matareya', 'ar' => 'المطرية'],
                ['en' => 'El Salam', 'ar' => 'السلام'],
                ['en' => 'Badr City', 'ar' => 'مدينة بدر'],
                ['en' => 'El Shorouk', 'ar' => 'الشروق'],
                ['en' => 'El Rehab', 'ar' => 'الرحاب'],
            ],
            'giza' => [
                ['en' => 'Giza', 'ar' => 'الجيزة'],
                ['en' => 'Dokki', 'ar' => 'الدقي'],
                ['en' => 'Mohandessin', 'ar' => 'المهندسين'],
                ['en' => '6th of October', 'ar' => 'السادس من أكتوبر'],
                ['en' => 'Sheikh Zayed', 'ar' => 'الشيخ زايد'],
                ['en' => 'Haram', 'ar' => 'الهرم'],
                ['en' => 'Faisal', 'ar' => 'فيصل'],
                ['en' => 'Imbaba', 'ar' => 'إمبابة'],
                ['en' => 'Boulaq El Dakrour', 'ar' => 'بولاق الدكرور'],
                ['en' => 'Agouza', 'ar' => 'العجوزة'],
                ['en' => 'Warraq', 'ar' => 'الوراق'],
                ['en' => 'Saft El Laban', 'ar' => 'صفط اللبن'],
                ['en' => 'Kerdasa', 'ar' => 'كرداسة'],
                ['en' => 'Atfih', 'ar' => 'أطفيح'],
                ['en' => 'El Badrashin', 'ar' => 'البدرشين'],
            ],
            'alexandria' => [
                ['en' => 'Alexandria', 'ar' => 'الإسكندرية'],
                ['en' => 'Borg El Arab', 'ar' => 'برج العرب'],
                ['en' => 'Montaza', 'ar' => 'المنتزه'],
                ['en' => 'Sidi Gaber', 'ar' => 'سيدي جابر'],
                ['en' => 'Smouha', 'ar' => 'سموحة'],
                ['en' => 'Miami', 'ar' => 'ميامي'],
                ['en' => 'El Agami', 'ar' => 'العجمي'],
                ['en' => 'Abu Qir', 'ar' => 'أبو قير'],
                ['en' => 'El Mandara', 'ar' => 'المندرة'],
                ['en' => 'Sidi Bishr', 'ar' => 'سيدي بشر'],
                ['en' => 'Stanley', 'ar' => 'ستانلي'],
                ['en' => 'Gleem', 'ar' => 'جليم'],
                ['en' => 'Bakos', 'ar' => 'باكوس'],
                ['en' => 'Karmoz', 'ar' => 'كرموز'],
            ],
            'qalyubia' => [
                ['en' => 'Banha', 'ar' => 'بنها'],
                ['en' => 'Shubra El Kheima', 'ar' => 'شبرا الخيمة'],
                ['en' => 'Qalyub', 'ar' => 'قليوب'],
                ['en' => 'Qaha', 'ar' => 'قها'],
                ['en' => 'El Khanka', 'ar' => 'الخانكة'],
                ['en' => 'Khusus', 'ar' => 'الخصوص'],
                ['en' => 'Toukh', 'ar' => 'طوخ'],
                ['en' => 'Kafr Shukr', 'ar' => 'كفر شكر'],
                ['en' => 'El Qanater El Khayreya', 'ar' => 'القناطر الخيرية'],
                ['en' => 'Obour', 'ar' => 'العبور'],
            ],
            'sharqia' => [
                ['en' => 'Zagazig', 'ar' => 'الزقازيق'],
                ['en' => 'Bilbeis', 'ar' => 'بلبيس'],
                ['en' => '10th of Ramadan', 'ar' => 'العاشر من رمضان'],
                ['en' => 'Minya El Qamh', 'ar' => 'منيا القمح'],
                ['en' => 'Abu Kabir', 'ar' => 'أبو كبير'],
                ['en' => 'Faqous', 'ar' => 'فاقوس'],
                ['en' => 'Hehia', 'ar' => 'ههيا'],
                ['en' => 'Awlad Saqr', 'ar' => 'أولاد صقر'],
                ['en' => 'El Husseiniya', 'ar' => 'الحسينية'],
                ['en' => 'San El Hagar', 'ar' => 'صان الحجر'],
                ['en' => 'Diyarb Negm', 'ar' => 'ديرب نجم'],
                ['en' => 'Kafr Saqr', 'ar' => 'كفر صقر'],
                ['en' => 'Ibrahimia', 'ar' => 'الإبراهيمية'],
                ['en' => 'El Salhia El Gedida', 'ar' => 'الصالحية الجديدة'],
            ],
            'dakahlia' => [
                ['en' => 'Mansoura', 'ar' => 'المنصورة'],
                ['en' => 'Talkha', 'ar' => 'طلخا'],
                ['en' => 'Mit Ghamr', 'ar' => 'ميت غمر'],
                ['en' => 'Dekernes', 'ar' => 'دكرنس'],
                ['en' => 'Belqas', 'ar' => 'بلقاس'],
                ['en' => 'Sherbin', 'ar' => 'شربين'],
                ['en' => 'Aga', 'ar' => 'أجا'],
                ['en' => 'Mit Salsil', 'ar' => 'ميت سلسيل'],
                ['en' => 'Gamasa', 'ar' => 'جمصة'],
                ['en' => 'Manzala', 'ar' => 'المنزلة'],
                ['en' => 'Sinbillawin', 'ar' => 'السنبلاوين'],
                ['en' => 'Nabaroh', 'ar' => 'نبروه'],
                ['en' => 'Bani Ubeid', 'ar' => 'بني عبيد'],
            ],
            'beheira' => [
                ['en' => 'Damanhur', 'ar' => 'دمنهور'],
                ['en' => 'Kafr El Dawwar', 'ar' => 'كفر الدوار'],
                ['en' => 'Rashid', 'ar' => 'رشيد'],
                ['en' => 'Edko', 'ar' => 'إدكو'],
                ['en' => 'Abu El Matamir', 'ar' => 'أبو المطامير'],
                ['en' => 'Hosh Issa', 'ar' => 'حوش عيسى'],
                ['en' => 'Shubrakhit', 'ar' => 'شبراخيت'],
                ['en' => 'Itay El Barud', 'ar' => 'إيتاي البارود'],
                ['en' => 'Kom Hamada', 'ar' => 'كوم حمادة'],
                ['en' => 'Delengat', 'ar' => 'الدلنجات'],
                ['en' => 'Mahmoudia', 'ar' => 'المحمودية'],
                ['en' => 'Wadi El Natrun', 'ar' => 'وادي النطرون'],
                ['en' => 'New Nubaria', 'ar' => 'النوبارية الجديدة'],
            ],
            'minya' => [
                ['en' => 'Minya', 'ar' => 'المنيا'],
                ['en' => 'Mallawi', 'ar' => 'ملوي'],
                ['en' => 'Beni Mazar', 'ar' => 'بني مزار'],
                ['en' => 'Maghagha', 'ar' => 'مغاغة'],
                ['en' => 'Samalut', 'ar' => 'سمالوط'],
                ['en' => 'Deir Mawas', 'ar' => 'دير مواس'],
                ['en' => 'Abu Qurqas', 'ar' => 'أبو قرقاص'],
                ['en' => 'Matai', 'ar' => 'مطاي'],
                ['en' => 'New Minya', 'ar' => 'المنيا الجديدة'],
            ],
            'sohag' => [
                ['en' => 'Sohag', 'ar' => 'سوهاج'],
                ['en' => 'Akhmim', 'ar' => 'أخميم'],
                ['en' => 'Girga', 'ar' => 'جرجا'],
                ['en' => 'Tahta', 'ar' => 'طهطا'],
                ['en' => 'Tama', 'ar' => 'طما'],
                ['en' => 'El Balyana', 'ar' => 'البلينا'],
                ['en' => 'El Maragha', 'ar' => 'المراغة'],
                ['en' => 'Dar El Salam', 'ar' => 'دار السلام'],
                ['en' => 'Saqulta', 'ar' => 'ساقلتة'],
                ['en' => 'El Monsha', 'ar' => 'المنشاة'],
                ['en' => 'Juhayna', 'ar' => 'جهينة'],
            ],
            'asyut' => [
                ['en' => 'Asyut', 'ar' => 'أسيوط'],
                ['en' => 'Dairut', 'ar' => 'ديروط'],
                ['en' => 'Manfalut', 'ar' => 'منفلوط'],
                ['en' => 'Abnub', 'ar' => 'أبنوب'],
                ['en' => 'El Badari', 'ar' => 'البداري'],
                ['en' => 'El Qusiya', 'ar' => 'القوصية'],
                ['en' => 'Sahel Selim', 'ar' => 'ساحل سليم'],
                ['en' => 'Abu Tig', 'ar' => 'أبو تيج'],
                ['en' => 'El Ghanayem', 'ar' => 'الغنايم'],
                ['en' => 'New Asyut', 'ar' => 'أسيوط الجديدة'],
            ],
            'monufia' => [
                ['en' => 'Shibin El Kom', 'ar' => 'شبين الكوم'],
                ['en' => 'Menouf', 'ar' => 'منوف'],
                ['en' => 'Sadat City', 'ar' => 'مدينة السادات'],
                ['en' => 'Tala', 'ar' => 'تلا'],
                ['en' => 'Berket El Sab', 'ar' => 'بركة السبع'],
                ['en' => 'Quesna', 'ar' => 'قويسنا'],
                ['en' => 'Ashmoun', 'ar' => 'أشمون'],
                ['en' => 'El Bagour', 'ar' => 'الباجور'],
                ['en' => 'El Shohada', 'ar' => 'الشهداء'],
            ],
            'gharbia' => [
                ['en' => 'Tanta', 'ar' => 'طنطا'],
                ['en' => 'El Mahalla El Kubra', 'ar' => 'المحلة الكبرى'],
                ['en' => 'Kafr El Zayat', 'ar' => 'كفر الزيات'],
                ['en' => 'Zifta', 'ar' => 'زفتى'],
                ['en' => 'Samannud', 'ar' => 'سمنود'],
                ['en' => 'Basyoun', 'ar' => 'بسيون'],
                ['en' => 'Qutour', 'ar' => 'قطور'],
                ['en' => 'El Santa', 'ar' => 'السنطة'],
            ],
            'kafr-el-sheikh' => [
                ['en' => 'Kafr El Sheikh', 'ar' => 'كفر الشيخ'],
                ['en' => 'Desouk', 'ar' => 'دسوق'],
                ['en' => 'Fuwwah', 'ar' => 'فوه'],
                ['en' => 'Baltim', 'ar' => 'بلطيم'],
                ['en' => 'Qallin', 'ar' => 'قلين'],
                ['en' => 'Burullus', 'ar' => 'البرلس'],
                ['en' => 'Sidi Salim', 'ar' => 'سيدي سالم'],
                ['en' => 'Bila', 'ar' => 'بيلا'],
                ['en' => 'Riad', 'ar' => 'الرياض'],
                ['en' => 'El Hamool', 'ar' => 'الحامول'],
                ['en' => 'Metoubes', 'ar' => 'مطوبس'],
            ],
            'faiyum' => [
                ['en' => 'Faiyum', 'ar' => 'الفيوم'],
                ['en' => 'Tamiya', 'ar' => 'طامية'],
                ['en' => 'Sinnuris', 'ar' => 'سنورس'],
                ['en' => 'Ibsheway', 'ar' => 'إبشواي'],
                ['en' => 'Itsa', 'ar' => 'إطسا'],
                ['en' => 'Yusuf El Sediek', 'ar' => 'يوسف الصديق'],
                ['en' => 'New Faiyum', 'ar' => 'الفيوم الجديدة'],
            ],
            'beni-suef' => [
                ['en' => 'Beni Suef', 'ar' => 'بني سويف'],
                ['en' => 'El Wasta', 'ar' => 'الواسطى'],
                ['en' => 'Nasser', 'ar' => 'ناصر'],
                ['en' => 'Ihnasia', 'ar' => 'إهناسيا'],
                ['en' => 'Beba', 'ar' => 'ببا'],
                ['en' => 'Sumusta', 'ar' => 'سمسطا'],
                ['en' => 'El Fashn', 'ar' => 'الفشن'],
                ['en' => 'New Beni Suef', 'ar' => 'بني سويف الجديدة'],
            ],
            'qena' => [
                ['en' => 'Qena', 'ar' => 'قنا'],
                ['en' => 'Nag Hammadi', 'ar' => 'نجع حمادي'],
                ['en' => 'Qus', 'ar' => 'قوص'],
                ['en' => 'Qift', 'ar' => 'قفط'],
                ['en' => 'Naqada', 'ar' => 'نقادة'],
                ['en' => 'Dishna', 'ar' => 'دشنا'],
                ['en' => 'Abu Tesht', 'ar' => 'أبو تشت'],
                ['en' => 'Farshut', 'ar' => 'فرشوط'],
                ['en' => 'New Qena', 'ar' => 'قنا الجديدة'],
            ],
            'aswan' => [
                ['en' => 'Aswan', 'ar' => 'أسوان'],
                ['en' => 'Edfu', 'ar' => 'إدفو'],
                ['en' => 'Kom Ombo', 'ar' => 'كوم أمبو'],
                ['en' => 'Daraw', 'ar' => 'دراو'],
                ['en' => 'Nasr El Nuba', 'ar' => 'نصر النوبة'],
                ['en' => 'Abu Simbel', 'ar' => 'أبو سمبل'],
                ['en' => 'New Aswan', 'ar' => 'أسوان الجديدة'],
                ['en' => 'El Sebaiya', 'ar' => 'السباعية'],
            ],
            'luxor' => [
                ['en' => 'Luxor', 'ar' => 'الأقصر'],
                ['en' => 'Esna', 'ar' => 'إسنا'],
                ['en' => 'Armant', 'ar' => 'أرمنت'],
                ['en' => 'El Toud', 'ar' => 'الطود'],
                ['en' => 'El Qurna', 'ar' => 'القرنة'],
                ['en' => 'New Tiba', 'ar' => 'طيبة الجديدة'],
                ['en' => 'El Bayadeya', 'ar' => 'البياضية'],
                ['en' => 'New Luxor', 'ar' => 'الأقصر الجديدة'],
            ],
            'damietta' => [
                ['en' => 'Damietta', 'ar' => 'دمياط'],
                ['en' => 'New Damietta', 'ar' => 'دمياط الجديدة'],
                ['en' => 'Ras El Bar', 'ar' => 'رأس البر'],
                ['en' => 'Faraskour', 'ar' => 'فارسكور'],
                ['en' => 'Zarqa', 'ar' => 'الزرقا'],
                ['en' => 'Kafr Saad', 'ar' => 'كفر سعد'],
                ['en' => 'Kafr El Battikh', 'ar' => 'كفر البطيخ'],
                ['en' => 'El Sirw', 'ar' => 'السرو'],
            ],
            'ismailia' => [
                ['en' => 'Ismailia', 'ar' => 'الإسماعيلية'],
                ['en' => 'Fayed', 'ar' => 'فايد'],
                ['en' => 'Qantara Sharq', 'ar' => 'القنطرة شرق'],
                ['en' => 'Qantara Gharb', 'ar' => 'القنطرة غرب'],
                ['en' => 'Tell El Kebir', 'ar' => 'التل الكبير'],
                ['en' => 'Abu Sweir', 'ar' => 'أبو صوير'],
                ['en' => 'Kassasin', 'ar' => 'القصاصين'],
            ],
            'port-said' => [
                ['en' => 'Port Said', 'ar' => 'بورسعيد'],
                ['en' => 'Port Fuad', 'ar' => 'بورفؤاد'],
                ['en' => 'El Manakh', 'ar' => 'المناخ'],
                ['en' => 'El Arab', 'ar' => 'العرب'],
                ['en' => 'El Zohour', 'ar' => 'الزهور'],
                ['en' => 'El Dawahi', 'ar' => 'الضواحي'],
                ['en' => 'El Sharq', 'ar' => 'الشرق'],
                ['en' => 'El Gharb', 'ar' => 'الغرب'],
            ],
            'suez' => [
                ['en' => 'Suez', 'ar' => 'السويس'],
                ['en' => 'Arbaeen', 'ar' => 'الأربعين'],
                ['en' => 'Ataqah', 'ar' => 'عتاقة'],
                ['en' => 'Ain Sokhna', 'ar' => 'العين السخنة'],
                ['en' => 'El Ganayen', 'ar' => 'الجناين'],
                ['en' => 'Faisal', 'ar' => 'فيصل'],
            ],
            'north-sinai' => [
                ['en' => 'Arish', 'ar' => 'العريش'],
                ['en' => 'Sheikh Zuweid', 'ar' => 'الشيخ زويد'],
                ['en' => 'Rafah', 'ar' => 'رفح'],
                ['en' => 'Bir El Abd', 'ar' => 'بئر العبد'],
                ['en' => 'Hasana', 'ar' => 'الحسنة'],
                ['en' => 'Nakhl', 'ar' => 'نخل'],
            ],
            'south-sinai' => [
                ['en' => 'Sharm El Sheikh', 'ar' => 'شرم الشيخ'],
                ['en' => 'Dahab', 'ar' => 'دهب'],
                ['en' => 'Nuweiba', 'ar' => 'نويبع'],
                ['en' => 'Saint Catherine', 'ar' => 'سانت كاترين'],
                ['en' => 'El Tor', 'ar' => 'الطور'],
                ['en' => 'Taba', 'ar' => 'طابا'],
                ['en' => 'Abu Zenima', 'ar' => 'أبو زنيمة'],
                ['en' => 'Abu Rudeis', 'ar' => 'أبو رديس'],
                ['en' => 'Ras Sedr', 'ar' => 'رأس سدر'],
            ],
            'red-sea' => [
                ['en' => 'Hurghada', 'ar' => 'الغردقة'],
                ['en' => 'Marsa Alam', 'ar' => 'مرسى علم'],
                ['en' => 'Safaga', 'ar' => 'سفاجا'],
                ['en' => 'Ras Ghareb', 'ar' => 'رأس غارب'],
                ['en' => 'El Quseir', 'ar' => 'القصير'],
                ['en' => 'Shalateen', 'ar' => 'شلاتين'],
                ['en' => 'Halaib', 'ar' => 'حلايب'],
                ['en' => 'El Gouna', 'ar' => 'الجونة'],
            ],
            'new-valley' => [
                ['en' => 'Kharga', 'ar' => 'الخارجة'],
                ['en' => 'Dakhla', 'ar' => 'الداخلة'],
                ['en' => 'Farafra', 'ar' => 'الفرافرة'],
                ['en' => 'Balat', 'ar' => 'بلاط'],
                ['en' => 'Paris', 'ar' => 'باريس'],
            ],
            'matrouh' => [
                ['en' => 'Marsa Matrouh', 'ar' => 'مرسى مطروح'],
                ['en' => 'El Alamein', 'ar' => 'العلمين'],
                ['en' => 'Sallum', 'ar' => 'السلوم'],
                ['en' => 'Siwa', 'ar' => 'سيوة'],
                ['en' => 'El Hamam', 'ar' => 'الحمام'],
                ['en' => 'El Dabaa', 'ar' => 'الضبعة'],
                ['en' => 'Sidi Barrani', 'ar' => 'سيدي براني'],
                ['en' => 'New Alamein', 'ar' => 'العلمين الجديدة'],
            ],
        ];

        foreach ($citiesByGovernorate as $govSlug => $cities) {
            $governorate = Governorate::query()->where('slug', $govSlug)->first();
            if (! $governorate) {
                continue;
            }

            foreach ($cities as $city) {
                City::firstOrCreate(
                    ['slug' => Str::slug($govSlug.'-'.$city['en'])],
                    [
                        'governorate_id' => $governorate->id,
                        'name' => $city,
                    ],
                );
            }
        }
    }
}
